config/routes.rb
DBPeople::Application.routes.draw do

  resources :stats

  resources :people

  root :to => 'people#index'

end

app/models/Person.rb
include RDF

class Person
	# endpoint = 'http://dbpedia.org/sparql'
	endpoint = 'http://live.dbpedia.org/sparql'

	# TODO:  IMPORTANT: Need to UNION with influencedBy property!

	# FIXME:  DEPRECATED
	def self.getInfluenced(personURI, depth=1)
		# Note: this query excludes other values in DBPedia that define influenced groups by subsetting to the dbpedia:Person class.
		query = "SELECT * WHERE { 
					<#{personURI}> <http://dbpedia.org/ontology/influenced> ?influenced . 
					?influenced a <http://dbpedia.org/ontology/Person> . }"

		peopleInfluenced = queryEndpoint('http://dbpedia.org/sparql', query, "csv")
		
		# Parse CSV into components, remove empty elements due to splitting on quotes (fix this) and 
		# removing the first element, because it is the column name.
		peopleInfluenced.split("\"").delete_if { |v| v.strip.empty? }[1,peopleInfluenced.length]
	end

	# FIXME:  DEPRECATED
	def self.getInfluencersOf(personURI, depth=1)
		
		query = "SELECT * WHERE { 
					?influencer <http://dbpedia.org/ontology/influenced> <#{personURI}> . 
					?influencer a <http://dbpedia.org/ontology/Person> . }"
		
		influencers = queryEndpoint('http://dbpedia.org/sparql', query, "csv")
		influencers.split("\"").delete_if { |v| v.strip.empty? }[1,influencers.length]

	end

	def self.getInfluencedJSON(personURI, depth=1)
		
		# TODO: Some entities use either birthDate or birthYear property.  Doing a JOIN will get both of these, but duplicates
		#       for all that have both.  DBpedia does not implement SPARQL 1.1 and so cannot do inner LIMITs on UNIONs.
		#       The following query will net duplicates, and could be deduplicated post-query.
		#  { ?influence <http://dbpedia.org/ontology/birthDate> ?influenceBirth } UNION { ?influence <http://dbpedia.org/ontology/birthYear> ?influenceBirth } .
		#       For now, choose the property most frequently used:
		#        count(?personA_birthYear):  4,321; count(?personA_birthDate):  13,870

		# Note: this query excludes other values in DBPedia that define influenced groups by subsetting to the dbpedia:Person class.
		query = "SELECT ?influence ?influenceName ?influenceBirth WHERE { 
					<#{personURI}> <http://dbpedia.org/ontology/influenced> ?influence . 
					?influence a <http://dbpedia.org/ontology/Person> . 
					?influence <http://xmlns.com/foaf/0.1/name> ?influenceName . 
					?influence <http://dbpedia.org/ontology/birthDate> ?influenceBirth .
				}"
		
		peopleInfluenced = queryEndpoint('http://dbpedia.org/sparql', query, "json")

		# Extract / Transcode JSON result
		ActiveSupport::JSON.decode(peopleInfluenced)['results']['bindings'].each do |record|
			puts "#{record['influence']['value']}"
			puts "#{record['influenceName']['value']}"
			puts "#{record['influenceBirth']['value']}"
		end

		puts peopleInfluenced
		
		return peopleInfluenced
	end

	def self.getInfluencersOfJSON(personURI, depth=1)
		
		# Note: this query excludes other values in DBPedia that define influenced groups by subsetting to the dbpedia:Person class.
		query = "SELECT ?influence ?influenceName ?influenceBirth WHERE { 
					?influence <http://dbpedia.org/ontology/influenced> <#{personURI}> . 
					?influence a <http://dbpedia.org/ontology/Person> . 
					?influence <http://xmlns.com/foaf/0.1/name> ?influenceName . 
					?influence <http://dbpedia.org/ontology/birthDate> ?influenceBirth .
		}"
		
		influencers = queryEndpoint('http://dbpedia.org/sparql', query, "json")
		
		puts influencers
		return influencers
	end



	# TODO:   Move this into its own helper or gem (is there a dbpedia gem?)
	# FIXME:  Rescue & handle "Request Timeout" situation
	# => 2013-02-28T08:14:53+00:00 app[web.1]: RestClient::RequestTimeout (Request Timeout):
	# => 2013-02-28T08:14:53+00:00 app[web.1]:   app/models/Person.rb:22:in `queryEndpoint'
	# => 2013-02-28T08:14:53+00:00 app[web.1]:   app/models/Person.rb:9:in `getInfluenced'
	# => 2013-02-28T08:14:53+00:00 app[web.1]:   app/controllers/people_controller.rb:3:in `index'
	def self.queryEndpoint(endpoint, query, format = "xml")
		# output options: "xml" (default), "json", "js", "n3", "csv"
		return RestClient.post endpoint, :query => query, :output => format
	end
end

app/models/stats.rb
class Stats < ActiveRecord::Base
  attr_accessible :hitcount
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	def index

		# Only do handling in rescue block, instead of doing these checks
		# that are almost guaranteed to work
		if params[:person_uri].nil? || params[:person_uri].empty?
			# TODO: Create a Stats.increment_hitcount method to do this
			stats = Stats.first
			stats.hitcount = stats.hitcount + 1
			stats.save
		end

		unless params[:person_uri].nil?
			if params[:person_uri].starts_with? 'http://dbpedia.org'
				begin
				
					@influenced = Person.getInfluenced(params[:person_uri])
					@influencers = Person.getInfluencersOf(params[:person_uri])

					@influencedJSON = Person.getInfluencedJSON(params[:person_uri])
					@influencersJSON = Person.getInfluencersOfJSON(params[:person_uri])

					# FIXME: Do this in the model and return a hash with influenced, 
					# influencers, and counts.  Better yet, do this all as a JSON
					# web-service / AJAX call.
					@forward_count = @influenced.count
					@backward_count = @influencers.count
				
				rescue RestClient::BadRequest
					puts @influencedJSON
					redirect_to '/', :notice => "DBPedia doesn't like this request.  :("
				end
			else
				redirect_to '/', :notice => "Currently, you must enter a valid DBPedia URI. Text search coming soon!"
			end
		end
	end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
    @stats = Stats.all
  end

  def show
    @stats = Stats.find(params[:id])
  end

  def new
    @stats = Stats.new
  end

  def create
    @stats = Stats.new(params[:stats])
    if @stats.save
      redirect_to @stats, :notice => "Successfully created stats."
    else
      render :action => 'new'
    end
  end

  def edit
    @stats = Stats.find(params[:id])
  end

  def update
    @stats = Stats.find(params[:id])
    if @stats.update_attributes(params[:stats])
      redirect_to @stats, :notice  => "Successfully updated stats."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @stats = Stats.find(params[:id])
    @stats.destroy
    redirect_to stats_url, :notice => "Successfully destroyed stats."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Exo:100|Strait' rel='stylesheet' type='text/css'>
  <title><%= content_for?(:title) ? yield(:title) : "influence discovery, by sands fish" %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
	<div id="header">
		<h1 class="logo"><a href="/" class="logo">influence discovery</a></h1>
		powered by <a href="http://dbpedia.org" class="subtitle">dbpedia.org</a>
		<span class="subtitle">a research & inspiration tool by <a href="http://sandsfish.com" class="subtitle">sands fish</a></span>
	</div>
	<div id="main">
    <div id="container">
      <div id="flash">
      	<% flash.each do |name, msg| %>
      	  <br/>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
  	  </div>
      <%= content_tag :h1, yield(:title) if show_title? %>
    </div>
		<%= yield %>
	</div>
	<br/>
	<div id="footer">
		<br/>
		<br/>
		powered by <a href="http://dbpedia.org" class="subtitle">dbpedia.org</a>
		<span class="subtitle">a research & inspiration tool by <a href="http://sandsfish.com" class="subtitle">sands fish</a></span>
		<br/>
	</div>
</body>
</html>

app/views/people/index.html.erb
<style>
  svg {
    background-color: white;
    border: 1px solid gray;
    display: block;
    margin-left: auto;
    margin-right: auto;
  }

  path:hover {
    stroke: rgb(30, 30, 30);
    stroke-width: 2px;
  }

  .highlight {
    stroke-width: 2px;
    stroke: rgb(70,130,180);
  }

  text {
    font-weight: bold
  }

  #searchbar {
    display: inline-block;
    margin-left: auto;
    margin-right: auto;
  }
</style>

<script type="text/javascript" src="assets/d3.v3.js"></script>
  <div style="width: 100%; text-align: center;">
  <div id="searchbar">
    <%= form_tag '/people', :method => :get do %>
      <%= text_field_tag 'person_uri', nil, :size => 75, :value => params[:person_uri] %>
      <%= submit_tag 'Analyze Influence', :class => 'button' %>
    <% end %>
  </div>
  </div>
  <% if params[:person_uri].nil? || params[:person_uri].empty? %>
	<span class="example_text">e.g. <a href="/people?person_uri=http%3A%2F%2Fdbpedia.org%2Fresource%2FNoam_Chomsky">http://dbpedia.org/resource/Noam_Chomsky</a></span>
  <% end %>
</div>

<div id="results-container">
  <div id="results">
    <div id="d3_timeline"/>

      <script type="text/javascript">

        d3.selection.prototype.moveToFront = function() {
          return this.each(function(){
            this.parentNode.appendChild(this);
          });
        };

        var influencedJSON = <%= @influencedJSON.html_safe unless @influencedJSON.nil? %>;
        var influencerJSON = <%= @influencersJSON.html_safe unless @influencersJSON.nil? %>;

        var svgHorizontalPadding = 120;

        // Just year formatting
        var dateFormatter = d3.time.format("%Y");

        // Data Setup
        var influencedData = influencedJSON.results.bindings;
        influencedData.sort( function(a,b) {
          return d3.ascending(new Date(a.influenceBirth.value), new Date(b.influenceBirth.value));
        });

        var influencerData = influencerJSON.results.bindings;
        influencerData.sort( function(a,b) {
          return d3.ascending(new Date(a.influenceBirth.value), new Date(b.influenceBirth.value));
        });

        // Check for empty data sets
        var doInfluencer = true;
        if(influencerData.length == 0) {
          doInfluencer = false;
        }

        var doInfluenced = true;
        if(influencedData.length == 0) {
          doInfluenced = false;
        }

        // Return unique years from list of individuals' birth years
        function getYears(data) {
          var influenceYears = data.map(function(obj) { return getBirthYear(obj); });
          return influenceYears.filter(function(v,i) { return influenceYears.indexOf(v) == i; });
        }

        // Gather unique influence years to aggregate individuals under
        var influencerYears = getYears(influencerData);
        var influencedYears = getYears(influencedData);

        var primaryColor = "rgb(70,130,180)"

        // Main SVG Canvas
        var svgWidth = 1200;
        var svgHeight = 500;
        var focusX = svgWidth/2;
        var focusY = svgHeight/2;
        var dataSpread = svgWidth / influencedJSON.results.bindings.length;
        var svg = d3.select("#d3_timeline").append("svg");
        svg.attr("width", svgWidth);
        svg.attr("height", svgHeight);
        svg.attr("class", "main_svg");

        // Horizontal Timeline Bar
        svg.append("rect")
           .attr("x", svgHorizontalPadding)
           .attr("y", focusY)
           .attr("height", 1)
           .attr("width", svgWidth-svgHorizontalPadding*2)
           .attr("fill", "rgb(80, 80, 80)");

        // Birth year time-scale translation and axis
        var scale_before = d3.scale
                      .linear()
                      .domain([
                        d3.min(influencerData, function(d) { return getBirthYear(d) }),
                        d3.max(influencerData, function(d) { return getBirthYear(d) }) ])
                      .range([svgHorizontalPadding, focusX - svgHorizontalPadding]);

        // Birth year time-scale translation and axis
        var scale_after = d3.scale
                      .linear()
                      .domain([
                        d3.min(influencedData, function(d) { return getBirthYear(d) }),
                        d3.max(influencedData, function(d) { return getBirthYear(d) }) ])
                      .range([focusX + svgHorizontalPadding, svgWidth - svgHorizontalPadding]);

        // Influenced Names
        if(doInfluenced) {
          var names_after = svg.selectAll("text.after")
           .data(influencedData)
           .enter()
           .append("text")
           .attr("class", "after")
           .attr("fill", primaryColor)
           .text( function(d) {
              return d.influenceName.value + " (" + getBirthYear(d) + ")";
           })
           .attr("transform", function(d, i) {
               return "translate(" + 0 + ", focusY)rotate(45)";
           })
           .transition()
           .attr("transform", function(d, i) {
               return "translate(" + scale_after(getBirthYear(d)) + ", " + (focusY-5) + ")rotate(-45)";
           })
           .duration(1800)
           .ease();
        }

        //Influencer Names
        if(doInfluencer) {
          var names_before = svg.selectAll("text.before")
           .data(influencerData)
           .enter()
           .append("text")
           .attr("class", "before")
           .attr("fill", primaryColor)
           .text( function(d) {
              return d.influenceName.value + " (" + getBirthYear(d) + ")";
           })
           .attr("transform", function(d, i) {
               return "translate(" + 0 + ", focusY)rotate(45)";
           })
           .transition()
           .attr("transform", function(d, i) {
               return "translate(" + scale_before(getBirthYear(d)) + ", " + (focusY+20) + ")rotate(45)";
           })
           .duration(1800)
           .ease();
        }

        // Before Control Points
        function getXControlPointBefore(d) {
          var controlOffset = (focusX - scale_before(getBirthYear(d)))/2;
          // TODO: Add Randomness in here
          return scale_before(getBirthYear(d)) + controlOffset;// + Math.random() * 30;
        }

        function getYControlPointBefore(d) {
          var controlOffset = (focusX - scale_before(getBirthYear(d))) / 80;
          // TODO: Add Randomness in here
          // ((Math.random()*-10)+130)
          return focusY/controlOffset;
        }

        // After Control Points
        function getXControlPointAfter(d) {
          var controlOffset = ((scale_after(getBirthYear(d)) - focusX) / 2);
          return scale_after(getBirthYear(d)) - controlOffset;
        }

        function getYControlPointAfter(d) {
          var controlOffset = (scale_after(getBirthYear(d)) - focusX) / 80;
          return focusY + (focusY * (1 - (1/controlOffset)));
        }

        // If there are influencers for this individual, draw arcs from them to the individual node
        if(doInfluencer) {
          var paths_before = svg.selectAll("path.before")
            .data(influencerData)
            .enter()
            .append("path")
            .attr("class", "before")
            .attr("fill", "transparent")
            .attr("stroke", "rgb(200, 200, 200)")
            .attr("d", function(d, i) {
              return "M " + focusX + " " + focusY + " Q 0 0, 0 " + focusY;
            })
            .on("click", function(d, i) { highlight(d, i); })
            .transition()
            .attr("d", function(d, i) {
              // maybe do a call to a function for this
              return "M " + scale_before(getBirthYear(d)) + " " + focusY +
                     " Q " + getXControlPointBefore(d) + " " + getYControlPointBefore(d) +
                     " , " + focusX + " " + focusY;
            })
            .duration(2000)
            .ease();
        }

        // If there are people influenced by this individual, draw arcs from the individual node to them
        if(doInfluenced) {
          var paths_after = svg.selectAll("path.after")
            .data(influencedData)
            .enter()
            .append("path")
            .attr("class", "after")
            .attr("fill", "transparent")
            .attr("stroke", "rgb(200, 200, 200)")
            .attr("d", function(d, i) {
              return "M " + focusX + " " + focusY + " Q 0 0, 0 " + focusY;
            })
            // .attr("transform", function(d, i) {
            //    return "translate(0, 50)"; })
            .on("click", highlight)
            .transition()
            .attr("d", function(d, i) {
              // maybe do a call to a function for this
              return "M " + focusX + " " + focusY +
                     " Q " + getXControlPointAfter(d) + " " + getYControlPointAfter(d) +
                     " , " + scale_after(getBirthYear(d)) + " " + focusY;
            })
            .duration(2000)
            .ease();
        }

/*
        // Temporary control point viz
        svg.selectAll("circle.controlpoint_before")
           .data(influencerData)
           .enter()
           .append("circle")
           .attr("class", "controlpoint_before")
           .attr("fill", "red")
           .attr("stroke", "rgb(255, 0, 0)")
           .attr("cx", function(d, i) { return getXControlPointBefore(d); })
           .attr("cy", function(d, i) { return getYControlPointBefore(d); })
           .attr("r", 5)
           .attr("fill-opacity", "0.5")
           .on("mouseover", function(d, i) { alert(getYControlPointBefore(d)); highlight(d, i); });

        svg.selectAll("circle.controlpoint_after")
           .data(influencedData)
           .enter()
           .append("circle")
           .attr("class", "controlpoint_after")
           .attr("fill", "red")
           .attr("stroke", "rgb(255, 0, 0)")
           .attr("cx", function(d, i) { return getXControlPointAfter(d); })
           .attr("cy", function(d, i) { return getYControlPointAfter(d); })
           .attr("r", 5)
           .attr("fill-opacity", "0.5")
           .on("mouseover", function(d, i) { alert(scale_after(getBirthYear(d))); highlight(d, i); });
*/

        // Set up year axis (after drawing other elements to avoid overdraw)
        var axis = d3.svg.axis().scale(scale_after).ticks(influencedData.length).tickFormat(d3.format("1"));
        svg.append("g")
           .attr("class", "axis")
           .attr("transform", "translate(0," + svgHeight + ")")
           .call(axis);

        // Return just the year of the birth date
        function getBirthYear(d) {
          return dateFormatter(new Date(d.influenceBirth.value));
        }

        // Highlight selected arcs
        function highlight(d, i) {

          // Grab element and class name using index
          var element = d3.selectAll("path.before")[0][i];
          var className = d3.select(element).attr("class");

          // Clear appropriate set of paths based on class name
          if(className.indexOf("before") != -1) {
            d3.selectAll("path.before").classed("highlight", false);
          } else {
            d3.selectAll("path.after").classed("highlight", false);
          }

          // Currently, this causes all the paths inside of this one to not be clickable
          // Possible Veroni solution?
          d3.select(element).classed("highlight", true).moveToFront();
        }

        // Influenced Nodes
        if(doInfluenced) {
          var circles_after = svg.selectAll("circle.after")
           .data(influencedData)
           .enter()
           .append("circle")
           .attr("class", "after")
           // .attr("fill", "rgb(70, 130, 180")
           .attr("fill", "rgb(80, 80, 80)")
           .attr("r", "2")
           .attr("cy", focusY+0.5)
           .attr("cx", 0)
           .transition()
           .attr("cx", function(d, i) {
               // return i * dataSpread + 0.5;
               return scale_after(getBirthYear(d));
           })
           .duration(1800)
           .ease();
        }

        // Influenced Nodes
        if(doInfluencer) {
          var circles_before = svg.selectAll("circle.before")
           .data(influencerData)
           .enter()
           .append("circle")
           .attr("class", "before")
           .attr("fill", "rgb(80, 80, 80")
           .attr("r", "2")
           .attr("cy", focusY+0.5)
           .attr("cx", 0)
           .transition()
           .attr("cx", function(d, i) {
               // return i * dataSpread + 0.5;
               return scale_before(getBirthYear(d));
           })
           .duration(1800)
           .ease();
         }

        // Focused Node
        svg.append("circle")
           .attr("r", 10)
           .attr("cx", focusX)
           .attr("cy", focusY)
           .attr("stroke", primaryColor)
           .attr("fill", "transparent");
        svg.append("circle")
           .attr("r", 7)
           .attr("cx", focusX)
           .attr("cy", focusY)
           .attr("fill", primaryColor);

      </script>

    <% unless @influenced.nil? || @influencers.nil? %>

	  <h2><%= link_to params[:person_uri], '/people?person_uri=' + u(params[:person_uri]) %> influenced <%= @forward_count %> people:</h2>

	  <% @influenced.each do |i| %>
		&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size: 75%">&#9658;</span>&nbsp;&nbsp;<%= link_to i, '/people?person_uri=' + u(i) %><br/>
	  <% end %>

	  <br/>

	  <h2><%= link_to params[:person_uri], '/people?person_uri=' + u(params[:person_uri]) %> was influenced by <%= @backward_count %> people:</h2>

	  <% @influencers.each do |i| %>
		&nbsp;&nbsp;&nbsp;&nbsp;&#9668;&nbsp;&nbsp;<%= link_to i, '/people?person_uri=' + u(i) %><br/>
	  <% end %>

	  <br/>
      <br/>
      <br/>
      <br/>
    <% else %>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
    <% end %>
  </div>
</div>

app/views/stats/_form.html.erb
<%= form_for @stats do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :hitcount %><br />
    <%= f.text_field :hitcount %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/stats/edit.html.erb
<% title "Edit Stats" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @stats %> |
  <%= link_to "View All", stats_path %>
</p>

app/views/stats/index.html.erb
&nbsp;&nbsp;&nbsp;&nbsp;<% title "Stats" %>
<table>
  <tr>
    <th>&nbsp;&nbsp;&nbsp;Hitcount</th>
  </tr>
  <% for stats in @stats %>
    <tr>
      <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= stats.hitcount %></td>
    </tr>
  <% end %>
</table>

app/views/stats/new.html.erb
<% title "New Stats" %>

<%= render 'form' %>

<p><%= link_to "Back to List", stats_path %></p>

app/views/stats/show.html.erb
<% title "Stats" %>

<p>
  <strong>Hitcount:</strong>
  <%= @stats.hitcount %>
</p>